/* =============================================================================
   Minecraft Trend Radar — DATA FILE
   -----------------------------------------------------------------------------
   This is the ONLY file the daily/weekly trend agent edits. The dashboard
   (index.html) reads window.TREND_DATA and renders it. Don't rename the keys.

   HOW TO ADD A WEEK:
   1. Add the new week label (week-start, e.g. "Jun 8") to `weeks` (end of list).
   2. For every entity, push ONE new number onto its `buzz` and `interest`
      arrays (same order as `weeks`). Update `subs` if it changed.
   3. Update `updated`, and refresh `movers` (up / down / new) for the week.
   4. Add any brand-new name as a new entity object (fill earlier weeks with
      null so the chart shows it starting partway in).

   SCALES / FIELDS:
     buzz     0-10  editorial "how much are kids talking about this" score
     interest 0-100 Google Trends search interest (objective; est. until wired)
     subs     subscriber count in millions (number) or null if unknown
     about    ~3-sentence blurb shown in the click-through detail panel
     ip       "mojang" = official Mojang game content. Shown in a SEPARATE
              awareness-only group and EXCLUDED from the merch "Hot Now" list
              and from movers. Red Lava Toys cannot make merch of Mojang IP;
              we track it only so we can talk to customers about it.
     link     OPTIONAL exact URL (e.g. the creator's YouTube channel).
   ============================================================================= */

window.TREND_DATA = {
  updated: "2026-09-01",
  weeks: ["Jun 1", "Jun 29", "Jul 6", "Jul 13", "Jul 20", "Jul 27", "Aug 3", "Aug 10", "Aug 17", "Aug 24", "Aug 31"],    // week-start labels, oldest -> newest

  entities: [
    // ---- CREATORS (the "make my skin look like them" names) ----
    { name: "Aphmau", type: "Creator", subs: 25.2, buzz: [8, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10], interest: [80, 87, 89, 89, 95, 98, 100, 100, 100, 100, 100], rising: true,
      about: "Aphmau (Jess) has ~25.2M subscribers and 29.1B+ lifetime views. Bonkers Toys retail launched August 2026 — debuted at SDCC (July) before nationwide rollout to Walmart, Target, Amazon, and Claire's: MyStreet 11\" plush characters (Aphmau Cat, Aaron Cat, Zane Cat, KC Cat, $21.99 each), MeeMeow Collector Figures mystery blind packs ($5.99 each, 8 character variants), Cat Café Surprise Set (17-piece, $49.99), Aphmau MyStreet Collector Figure 4-Pack featuring Aphmau, Aaron, Zane, KC ($27.99). Dragon MeeMeow Wave 2 Gemstone Dragons at Target + Walmart; MeeMeow Litter 4 'Under the Sea' now live on Walmart (Dolphin Cat, Jellyfish Cat, Turtle Cat, Seahorse Cat, Octopus Cat, Whale Cat, Lobster Cat, Stingray Cat) — expanding the mystery-blind category. eBay secondary market listings signal steady demand; line is now 7+ weeks on shelf with no reported retailer sell-out. MyStreet Season 7 'Faded Memories' confirmed November 2026 premiere; Season 8 ('One Last Time') confirmed as the series finale — complementary custom product alongside the official line remains the viable approach." },
    { name: "Maizen", type: "Creator", subs: 23, buzz: [9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10], interest: [78, 85, 87, 88, 90, 92, 97, 98, 99, 100, 100], rising: true,
      about: "Maizen (22.9M subs per Variety/pocket.watch May 2026; 23B+ lifetime views, ranked #1 gaming channel globally) makes story-driven Minecraft skits built around the 'JJ and Mikey' characters. The JJ & Mikey series streams live on Tubi, The Roku Channel, and Ryan and Friends Plus (pocket.watch global franchise deal, May 2026). Juniper worldwide merch drop LIVE — full cast lineup: JJ Rabbit Plush ($34.99), Mikey Turtle Plush ($34.99), Banana Kid Plush ($34.99), JJ & Mikey T-Shirt ($29.99), plus Carrie Cat & Banana Kid Plush Bundle at maizen.hellojuniper.com / maizen.shop; Carrie Cat sold out — window closes September 15 (14 days remaining as of Sep 1); JJ & Mikey plushies confirmed back and on sale per maizen.com. Bonkers Toys plush + blind-boxes Spring 2027 and Scholastic books early 2027 confirmed — that Spring 2027 retail gap remains the custom-merch window; the Juniper window closing Sep 15 is a live demand signal, not competition." },
    { name: "Mikecrack", type: "Creator", subs: 58.6, buzz: [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7], interest: [72, 71, 71, 71, 71, 72, 72, 72, 72, 72, 72], rising: false,
      about: "Mikecrack is the most-subscribed Spanish YouTuber at ~58.6M subs (ranked #72 globally as of July 2026) and is enormous with younger and Spanish-speaking kids. The Los Compas trio (Mikecrack, ElTrollino, Timba VK) book series has sold 31M+ copies worldwide across 10+ titles. 'Mikecrack y la Superarma Secreta' — his animated-series live spectacular — has 2026/2027 tour dates on Ticketmaster Mexico, keeping the IP visibly in market." },
    { name: "Jelly", type: "Creator", subs: 23, buzz: [7, 5, 3, 3, 3, 3, 2, 1, 1, 1, 1], interest: [68, 59, 50, 39, 30, 22, 5, 1, 1, 1, 1], rising: false,
      about: "Jelly is a top kid-friendly Minecraft YouTuber (~23M subs) known for short, easy-to-watch videos. Year-long slide is at floor as of August 2026 — no new series, hook content, or franchise announcement; interest at 1, effectively catalog-only with no active trend drivers and no recovery signals." },
    { name: "MrBeast Gaming", type: "Creator", subs: 42, buzz: [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6], interest: [73, 71, 71, 71, 71, 70, 67, 63, 57, 42, 34], rising: false,
      about: "MrBeast Gaming is the gaming channel of mega-creator MrBeast — whose main channel crossed 500M subscribers on June 12, 2026, a YouTube first. The Gaming sub-channel (~42M subs) leans on big-budget Minecraft challenges, prizes, and spectacle. Less about one character and more about event-style videos kids love; search interest drifting steadily as audience attention shifts to newer formats." },
    { name: "SSundee", type: "Creator", subs: 25.45, buzz: [8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9], interest: [64, 66, 72, 76, 79, 83, 93, 98, 99, 100, 100], rising: true,
      about: "SSundee (25.45M subs, ~4 uploads/week, 2.56% engagement) is a top US Minecraft creator known for funny commentary and pop-culture mod drops. The Crundee reunion with Crainer is confirmed fully active — Crundee Craft modpack last updated July 19, 2026, confirming ongoing series development; active series include Pixelmon Season 1 and Sky Factory with Crainer. Interest holds at 100 for a second consecutive week — all-time high and the 21st consecutive week of upward movement. Zero official toy line = strongest open US-creator custom merch slot alongside Alan Becker." },
    { name: "LankyBox", type: "Creator", subs: 42, buzz: [7, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0], interest: [65, 55, 20, 9, 5, 1, 0, 0, 0, 0, 0], rising: false,
      about: "LankyBox is a 42M-sub duo known for 'brainrot'-style Minecraft skits. Confirmed quit — no uploads since ~April 2026 (41+ weeks); fan analysis videos and the Adam McArthur / Justin Kroma partnership-split story are the dominant narrative on TikTok. TikTok Shop (748K+ items sold historically) and retail remain live passively on existing SKUs at effectively zero interest. Channel is finished — do not invest in LankyBox-adjacent product for 2026-2027." },
    { name: "CaseOh", type: "Creator", subs: 10.95, buzz: [7, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9], interest: [63, 68, 76, 82, 85, 86, 91, 92, 93, 95, 96], rising: true,
      about: "CaseOh has ~10.95M YouTube subscribers (2.44B+ total views, 4.84% engagement rate; ranked #509 US on YouTube). Summer Collection active at caseohgames.com (Flat Earth Hoodie $60, Slay Sweatshirt $60, Gahook Hoodie $70); no fall 2026 drop announced yet. Cicis Pizza 'Mac & CaseOh Pizza' nationwide collab ongoing throughout 2026 with quarterly social activations; Starforge Systems gaming-PC collab confirmed. No official toy line exists = open creator slot, though CaseOh's core audience skews teen/young-adult — most viable if targeting older-sibling influence on younger kids." },
    { name: "EYstreem", type: "Creator", subs: 13.76, buzz: [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8], interest: [74, 76, 76, 77, 77, 82, 87, 91, 95, 99, 100], rising: true,
      about: "EYstreem is Australia's most-watched global gaming YouTuber (~13.76M subs). Spawnpoint Media — his production company — confirmed in June 2026 Tubefilter that 'brand partnerships and merchandise are significantly bigger businesses than their content business,' with Microsoft, McDonald's, and LEGO as prior brand partners. Milo plush restocked and shipping at miloandchip.com ($29.99, 'before they sell out again'); Chip plush on pre-order (first Chip run not yet shipped); first Milo run sold out in two weeks with 4,000 orders and zero paid marketing. EYstreem interest hits 100 this week, matching the peak held by Chip & Milo, JJ & Mikey, Alan Becker, and SSundee. A major toy retail partnership is the most likely near-term catalyst — Spawnpoint's stated strategy strongly signals one is coming." },
    { name: "DanTDM", type: "Creator", subs: 29, buzz: [6, 6, 6, 6, 6, 6, 6, 5, 3, 2, 1], interest: [58, 58, 58, 57, 57, 54, 47, 36, 14, 3, 2], rising: false,
      about: "DanTDM is a long-running British Minecraft creator (~29M subs) active since 2012. Known for clean, family-friendly Let's Plays and mod showcases. In 2026 he is consulting with Mojang Studios and Merlin Entertainments on a Minecraft World theme-park development. Interest at 2 as of August 31 — the steepest consecutive-week decline this tracker has logged for him (36→14→3→2); a trusted evergreen name but generating zero kid-audience interest; catalog-only territory with no recovery signals." },
    { name: "PrestonPlayz", type: "Creator", subs: null, buzz: [7, 7, 9, 9, 9, 9, 9, 9, 9, 9, 9], interest: [62, 63, 72, 74, 75, 76, 78, 81, 84, 90, 91], rising: true,
      about: "PrestonPlayz's Bonkers Toys line is fully on shelf at Target and Amazon: Series 1 mini figures (Bloxton, PrestonPlayz, Preston 303, Shining Preston, Preston, Cactus Jones 6-pack), Mystery Merch Box (11 collectibles incl. limited-edition plushies, figures, posters, trading cards), plus the NAPPA Award-winning Pleb Slayer light-up sword and Mini Mystery Plush. Family of channels totals 66M combined subscribers and 22B views. Benchmark these SKUs for format and price-point — they are live competition on shelf now." },
    { name: "Dream", type: "Creator", subs: 31.5, buzz: [5, 5, 5, 5, 5, 5, 5, 3, 2, 1, 1], interest: [53, 52, 50, 47, 46, 38, 19, 10, 4, 2, 1], rising: false,
      about: "Dream (Clay) is one of the most famous US Minecraft names (~31.5M subs), known for 'Minecraft Manhunt' and speedrun content. More active in 2026 than his interest score suggests: Minecraft Manhunt 2 is an ongoing series, and his MCPVP server expanded to 38 worldwide locations in April 2026. However, his audience has drifted to teens — the 5–10 age group is largely not watching — and interest for that cohort is at 1 as of August 31, at absolute floor with no recovery signal." },
    { name: "Unspeakable", type: "Creator", subs: null, buzz: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], interest: [51, 50, 50, 50, 50, 49, 45, 40, 32, 18, 12], rising: false,
      about: "Unspeakable is a 'loud,' high-energy creator known for challenges, builds and real-life crossovers. The big personality and colorful thumbnails play well with younger viewers. A long-standing staple of the kid-Minecraft scene with slow but steady interest drift downward through 2026." },
    { name: "TommyInnit", type: "Creator", subs: 12, buzz: [5, 5, 5, 4, 4, 4, 4, 3, 1, 1, 1], interest: [49, 49, 47, 41, 34, 26, 8, 3, 1, 1, 1], rising: false,
      about: "TommyInnit is a hugely popular British creator (~12M subs) who rose through Minecraft SMP servers and streams. He shifted to selective content in 2026 ('100 Questions with Tom Simons' interview series, first MC Championship appearance in ~2 years). Interest at 1 as of August 31, at floor — steady drift to teens continues with no recovery signal for the 5–10 cohort." },
    { name: "Wisp", type: "Creator", subs: null, buzz: [4, 4, 4, 4, 4, 4, 4, 3, 1, 1, 1], interest: [46, 44, 42, 37, 34, 25, 7, 3, 1, 1, 1], rising: false,
      about: "Wisp makes 'wild mod' Minecraft videos that are chaotic, funny and unpredictable. The light-hearted tone keeps it broadly kid-friendly. Interest at 1 as of August 31 with no major new hook to reverse the trend — effectively at floor." },
    { name: "Stampy", type: "Creator", subs: null, buzz: [4, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2], interest: [37, 35, 33, 29, 25, 15, 2, 1, 1, 1, 1], rising: false,
      about: "Stampy (Stampy Cat) is the original kid-safe Minecraft creator, voiced as a cheerful cartoon cat. His long-running 'Lovely World' series is wholesome and narrative. A nostalgic classic — more grandparent-familiar than kid-current in 2026; interest at 1 and holding at floor." },
    { name: "Craftee", type: "Creator", subs: 5.2, buzz: [null, 6, 2, 2, 2, 2, 2, 2, 2, 2, 2], interest: [null, 50, 35, 23, 15, 5, 0, 0, 0, 0, 0], rising: false,
      about: "Craftee is a purely Minecraft-focused creator (~5M subs, ~12M monthly views) who appears on every curated 'kid-safe' list — no profanity, challenge and creative gameplay targeting ages 5–10. The craftee.store plush lineup (Classic Plushie $29.99, Golden variant, Chester plushie $26.99) remains available but generating no buzz. Subscriber growth stalled near zero; no franchise deals, retail expansion, or new drops detected through August 2026. Firmly catalog-only territory — interest at floor." },

    { name: "OMZ", type: "Creator", subs: 6.06, buzz: [null, null, 7, 7, 7, 7, 7, 9, 9, 9, 9], interest: [null, null, 60, 68, 72, 80, 85, 91, 94, 96, 97], rising: true,
      about: "OMZ (Omz Crew) is an American Minecraft roleplay YouTuber (~6.08M subscribers) generating ~32M monthly views as of August 2026. The 'new member' narrative arc continues to sustain engagement; the full Crew (Omz, Roxy, Crystal, Lily, Megan, Kevin) remains active. Squish Plushies Bundle active on Amazon and Walmart; Omz & Roxy Plush and Shirt Bundle live on Amazon (B0FLLL8MWS), expanding the merch lineup beyond the core Omz character. Core bundle still sold out across most sizes. Expanding retail footprint + persistent sell-out on core SKUs = robust demand — no exclusive toy deal yet = open slot in the RP-server niche." },

    { name: "Yarik Paw", type: "Creator", subs: 5.4, buzz: [null, null, null, null, 7, 8, 8, 8, 8, 8, 8], interest: [null, null, null, null, 57, 70, 76, 78, 82, 84, 85], rising: true,
      about: "Yarik Paw (@YarikPawGames) is a Ukrainian creator pioneering 'cinematic Minecraft' — episodic stories with emotional arcs and cliffhangers — at ~5.4M subscribers on his main Minecraft channel, 3.5B lifetime views. His secondary channel YarikPawReal (toy/food testing in reaction style) hit 500M+ views in its first 75 days (Aug–Oct 2025) — one of the fastest-growing YouTube projects of 2025. No licensing deal or franchise announcement found as of August 2026 — notable white space given the defined character roster and proven appetite for story-Minecraft product, but no confirmed catalyst." },

    // ---- FAN / ANIMATION CHARACTERS (merch-eligible — NOT Mojang's mobs) ----
    // Animated character duos — extremely high recognition w/ 6-10 y/o; CONFIRMED top sellers at Red Lava Toys shows.
    { name: "JJ & Mikey", type: "Character/Mob", subs: null, buzz: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10], interest: [96, 97, 98, 98, 98, 98, 100, 100, 100, 100, 100], rising: true,
      about: "JJ and Mikey are the lead characters of Maizen's animated Minecraft skits — streaming live on Tubi, The Roku Channel, and Ryan and Friends Plus (pocket.watch franchise deal, May 2026). Juniper worldwide merch drop LIVE — full cast lineup: JJ Rabbit Plush ($34.99), Mikey Turtle Plush ($34.99), Banana Kid Plush ($34.99), JJ & Mikey T-Shirt ($29.99), plus Carrie Cat & Banana Kid Plush Bundle at maizen.hellojuniper.com / maizen.shop; Carrie Cat Plush sold out; JJ & Mikey plushies confirmed back and on sale; window closes September 15, 2026 (14 days remaining as of Sep 1). Bonkers Toys plush + blind-boxes Spring 2027 and Scholastic books early 2027 confirmed — Spring 2027 retail gap remains the custom-merch window; the Juniper window closing Sep 15 signals active demand and is NOT competition with custom product. Confirmed #1 top sellers at Red Lava Toys shows." },
    { name: "Nico & Cash", type: "Character/Mob", subs: null, buzz: [10, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9], interest: [90, 86, 87, 88, 88, 89, 90, 92, 94, 96, 96], rising: true,
      about: "Nico and Cash are a paired-character Minecraft animation duo — Cash's channel hit 11M subscribers on June 8, 2026; Nico at ~4.9M and climbing (30K+ subs/month, 11.57M views in the last 30 days). Official store at cashandnico.com includes plushies, shirts, stickers, comic books, and a skate toy line; Youtooz collab active with Cash Plush (9in), Nico Plush (9in), and Meebo Plush now added to the lineup. Amazon presence confirmed with ongoing sales velocity. A durable catalog performer with proven show-table demand and growing Youtooz collab depth." },
    { name: "Chip & Milo", type: "Character/Mob", subs: 4.1, buzz: [9, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9], interest: [85, 83, 90, 93, 94, 96, 98, 100, 100, 100, 100], rising: true,
      about: "Milo and Chip are an animated-Minecraft duo from EYstreem's Spawnpoint Media (4.1M subs). 16 billion watch minutes May–Oct 2025 is comparable to SpongeBob SquarePants. Milo plush restocked at miloandchip.com ($29.99) with 'before they sell out again' urgency — first run sold out in two weeks with 4,000 orders and zero paid marketing; Chip plush on pre-order (first Chip run not yet shipped). Three seasons streaming: S1 Amazon Prime Video; S2–S3 Roku/Tubi. No big-box retail deal confirmed yet — SpongeBob-scale watch data + confirmed plush demand cycle + zero big-box deal = single most underserved IP on the board." },
    { name: "Alan Becker (AvM)", type: "Character/Mob", subs: 33.9, buzz: [8, 8, 9, 10, 10, 10, 10, 10, 10, 10, 10], interest: [70, 77, 85, 98, 99, 95, 99, 100, 100, 100, 100], rising: true,
      about: "Alan Becker's color-coded stick figures — The Second Coming, King Orange, Yellow, Green, Blue, and Red — star in 'Animation vs. Minecraft' (~33.9M subs, gaining ~300K/month). AVM Shorts Episode 40 'Creeper Clan' RELEASED August 29, 2026 — ending the 20-week wait since Episode 39 'The Aether' (April 18): Red and Blue discover an underground creeper civilization led by a character called Crepe; episode live and views climbing fast. 3rd Annual Popularity Poll closes Sep 4, 2026 (3 days remaining as of Sep 1) — results will confirm top character-demand ranking. Animation VERSUS fighting game targets June 2028. Zero mass-retail despite 33.9M+ subs: six-character sticker-sheet/pin artwork must be print-ready NOW to capture peak episode demand — this is the largest under-served retail white space in creator-Minecraft merch." },

    // ---- FORMATS / TOPICS (what kind of videos they're glued to) ----
    { name: "'Minecraft BUT…'", type: "Format", subs: null, buzz: [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7], interest: [61, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62], rising: false,
      about: "'Minecraft BUT…' is a dominant format where a normal playthrough is twisted by one wild rule or mod (e.g. 'Minecraft BUT everything is giant'). It's build/challenge/reaction content that's endlessly remixable. CaseOh's Hardcore format is the current evolution of this template." },
    { name: "Brainrot skits", type: "Format", subs: null, buzz: [7, 6, 2, 1, 1, 1, 1, 1, 1, 1, 1], interest: [63, 60, 42, 27, 16, 7, 1, 1, 1, 1, 1], rising: false,
      about: "'Brainrot' skits are chaotic, sensory-overload short videos using Minecraft skins to act out absurd stories. LankyBox's TikTok Shop confirmed 748K+ items sold historically — this audience converts directly to buyers at high volume. LankyBox confirmed quit (41+ weeks, no uploads since ~April 2026) and no replacement creator has emerged as of August 2026. Format interest at floor (1) — no recovery signals." },
    { name: "Roleplay servers", type: "Format", subs: null, buzz: [5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6], interest: [46, 48, 51, 57, 64, 70, 79, 83, 88, 92, 94], rising: true,
      about: "Minecraft roleplay (RP) servers are fictional worlds with their own economies, governments and ongoing storylines. OMZ Crew's active storylines, expanding character roster, and bundle sell-out confirm the format's commercial strength. Interest at 94 as of August 31, a new high and still the strongest rising format on the board. Popular with kids who love the 'pretend' and community side." },

    // ---- MOJANG IP — official game content (CUSTOMER AWARENESS ONLY, not merch) ----
    { name: "Baby mobs (Tiny Takeover)", type: "Character/Mob", ip: "mojang", subs: null, buzz: [4, 4, 2, 2, 1, 0, 0, 0, 0, 0, 0], interest: [50, 43, 28, 14, 5, 1, 0, 0, 0, 0, 0], rising: false,
      about: "The March 2026 'Tiny Takeover' drop redesigned every baby farm animal — puppies, kittens, piglets, calves, chicks, lambs, ocelots and bunnies — for maximum cuteness. Now 5+ months post-launch, the initial viral wave has fully settled and interest is at floor. Official Mojang content: great to know about for customer chats, but NOT something Red Lava Toys can make merch of." },
    { name: "Sulfur cube", type: "Character/Mob", ip: "mojang", subs: null, buzz: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6], interest: [54, 55, 55, 56, 56, 57, 60, 62, 65, 68, 70], rising: true,
      about: "The sulfur cube is a Minecraft mob that can absorb blocks — a mechanic unlike anything else in the game, driving lots of reaction/explainer videos. Official Mojang content: worth knowing for customer conversations, but not merch-eligible for Red Lava Toys." },
    { name: "A Minecraft Movie", type: "Format", ip: "mojang", subs: null, buzz: [6, 7, 9, 9, 9, 9, 6, 4, 3, 3, 3], interest: [62, 68, 75, 77, 78, 70, 50, 31, 13, 5, 4], rising: false,
      about: "The live-action/animated Warner Bros. film (April 2025) continues to drive streaming discovery; post-summer cooling deepens — interest now at 4. Sequel 'A Minecraft Movie Squared' (officially titled at Minecraft Live, May 2026; releasing July 23, 2027) — production in Moab, Utah for desert location filming. Confirmed cast: Momoa, Black, Brooks, Hansen, Coolidge; Kirsten Dunst as Alex (replacing Kate McKinnon); Matt Berry reprising Nitwit villager. Mojang/WB IP — strong customer-conversation context, not merch-eligible for Red Lava Toys." },
    { name: "Netflix Minecraft Series", type: "Format", ip: "mojang", subs: null, buzz: [null, null, 9, 9, 9, 7, 4, 2, 1, 1, 1], interest: [null, null, 74, 89, 86, 72, 47, 22, 6, 1, 1], rising: false,
      about: "WildBrain/Flying Bark CG-animated series (head writer: A.C. Bradley; showrunners Kevin Adams and Joe Ksander) — premiered June 24, 2026 on Netflix; now 10+ weeks live as of August 31. Features entirely new characters (not existing game characters); no character names publicly revealed. Series has NOT appeared in Netflix Top 10 and no Season 2 announcement has been made — a soft launch that has not broken through culturally. Interest at 1 and at floor with no recovery signals. NOT merch-eligible for Red Lava Toys." },
    { name: "Minecraft Dungeons II", type: "Format", ip: "mojang", subs: null, buzz: [null, null, null, null, 5, 6, 10, 10, 10, 10, 10], interest: [null, null, null, null, 42, 55, 91, 99, 100, 100, 100], rising: true,
      about: "Minecraft Dungeons II (developed with Double Eleven) — releasing September 29, 2026 (28 days away); Xbox Game Pass day-one inclusion confirmed August 15, 2026. Platforms: PS5, Xbox Series X|S, Switch, Switch 2, PC (Steam + Microsoft Store). Standard $29.99, Deluxe $49.99; pre-order bonus (expires Sep 29): 2 hero skins + Twisted cape + Twisted chicken pet. Gamescom (Cologne, Aug 25–30) concluded — public playable demo at Xbox booth (140 gaming stations) and Nintendo booth; Brave Haven hub town and minecart fast-travel system revealed; press hands-on coverage embargo LIFTED September 1, 2026 — full media coverage wave now live. Mattel: Twisted Warden, Blub, and Baby Sifter Plush (8-inch) live on shop.mattel.com; LEGO 21591 'The Twisted Warden Battle' ($59.99) on sale since Aug 1. Interest 100. Official Mojang content — NOT merch-eligible for Red Lava Toys." }
  ],

  // Merch-eligible names ONLY (never Mojang IP).
  movers: {
    up:   ["Alan Becker (AvM)", "EYstreem", "OMZ", "PrestonPlayz"],
    down: ["MrBeast Gaming", "Unspeakable", "DanTDM"],
    new:  []
  },

  headline: "SEP 1 — ALAN BECKER (AvM) Ep 40 'Creeper Clan' LIVE (released Aug 29, ending 20-week wait): Red & Blue star in underground creeper-civilization arc; views climbing fast; 3rd Annual Popularity Poll closes Sep 4 (3 days) — six-character sticker-sheet/pin artwork must be PRINT-READY NOW to capture peak demand; zero official toy line = largest open slot in creator-Minecraft merch. JJ & MIKEY JUNIPER: 14 days to Sep 15 window close — Carrie Cat still sold out, JJ Rabbit + Mikey Turtle back on sale; Banana Kid ships now; custom sticker/accessory packs needed NOW — Bonkers line not until Spring 2027. SSUNDEE: Interest 100, second consecutive week (21 consecutive weekly gains); Crundee active (Pixelmon S1 + Sky Factory); zero official toy line = strongest open US-creator slot. EYSTREEM: Interest 100; Milo restocked, Chip pre-order live; no big-box deal = #1 underserved IP by watch-time. OMZ: Interest 97; Amazon Original Bundle (B0GY9NCM62) active; Roxy + Omz Bundle live. PRESTONPLAYZ: Interest 91; Bonkers line fully live at Target + Amazon — benchmark these SKUs. NICO & CASH: Interest 96; Youtooz collab (Cash, Nico, Meebo) deepening. APHMAU: Retail line 7+ weeks on shelf; Season 7 Nov 2026. DanTDM: Interest 2, catalog-only (steepest decline tracked: 36→14→3→2). MrBeast Gaming: Interest 34, buzz cut to 6 — accelerating decline. (Mojang context: Dungeons II — press embargo LIFTED Sep 1; Sep 29 launch 28 days away; interest 100. Netflix Minecraft Series: no Top 10, interest 1 at floor. A Minecraft Movie Squared: production in Moab, interest 4.)"
};
