/* =============================================================================
   Minecraft Trend Radar — DATA FILE
   -----------------------------------------------------------------------------
   This is the ONLY file the daily/weekly trend agent edits. The dashboard
   (index.html) reads window.TREND_DATA and renders it. Don't rename the keys.

   HOW TO ADD A WEEK:
   1. Add the new week label (week-start, e.g. "Jun 8") to `weeks` (end of list).
   2. For every entity, push ONE new number onto its `buzz` and `interest`
      arrays (same order as `weeks`). Update `subs` if it changed.
   3. Update `updated`, and refresh `movers` (up / down / new) for the week.
   4. Add any brand-new name as a new entity object (fill earlier weeks with
      null so the chart shows it starting partway in).

   SCALES / FIELDS:
     buzz     0-10  editorial "how much are kids talking about this" score
     interest 0-100 Google Trends search interest (objective; est. until wired)
     subs     subscriber count in millions (number) or null if unknown
     about    ~3-sentence blurb shown in the click-through detail panel
     ip       "mojang" = official Mojang game content. Shown in a SEPARATE
              awareness-only group and EXCLUDED from the merch "Hot Now" list
              and from movers. Red Lava Toys cannot make merch of Mojang IP;
              we track it only so we can talk to customers about it.
     link     OPTIONAL exact URL (e.g. the creator's YouTube channel).
   ============================================================================= */

window.TREND_DATA = {
  updated: "2026-08-07",
  weeks: ["Jun 1", "Jun 29", "Jul 6", "Jul 13", "Jul 20", "Jul 27", "Aug 3"],    // week-start labels, oldest -> newest

  entities: [
    // ---- CREATORS (the "make my skin look like them" names) ----
    { name: "Aphmau", type: "Creator", subs: 25.2, buzz: [8, 9, 9, 9, 10, 10, 10], interest: [80, 87, 89, 89, 95, 98, 100], rising: true,
      about: "Aphmau (Jess) has ~25.2M subscribers and 29.65B+ lifetime views. Bonkers Toys retail launched in August 2026 with SDCC debut (Booth #221, July 2026) before nationwide rollout to Amazon, Walmart, Target, Claire's, and Smyths Toys Superstores: MyStreet Classic Plush (Aphmau Cat, Garroth Cat, Travis Cat), MyStreet Collector Figure 4-Pack (Aphmau, Aaron, Zane, KC — $27.99), MeeMeow Collector Figures mystery packs including Litter 7 Elemental theme (Water, Earth, Fire, Light, Lightning, Ice, Air, Dark Cat — 8 variants), and the Cat Café Surprise Set (17-piece, SRP $49.99). 'I Wouldn't Change A Thing' (MyStreet: One Last Time theme song) confirmed; Season 8 One Last Time — the final MyStreet season — is in production. With the five-retailer nationwide rollout now live as of August 2026, the custom-merch window is at its narrowest; complementary product alongside her aesthetic (not duplicating official SKUs) is the only viable remaining approach." },
    { name: "Maizen", type: "Creator", subs: 23, buzz: [9, 9, 9, 9, 9, 9, 10], interest: [78, 85, 87, 88, 90, 92, 95], rising: true,
      about: "Maizen (22.9M subs per Variety May 2026; 23B+ lifetime views, ranked #1 gaming channel globally) makes story-driven Minecraft skits built around the 'JJ and Mikey' characters. The JJ & Mikey TV series is now simultaneously live across four platforms — Hulu (Creator Essentials Season 1, 15 episodes), Tubi, Roku, and Ryan and Friends Plus — all streaming as of summer 2026. Official JJ & Mikey plushies confirmed in stock at maizen.junipercreates.com alongside the Carrie Cat & Banana Kid Plush Bundle ($34.99 each). Pocket.watch deal locks in Scholastic books early 2027 and Bonkers Toys plush + blind-boxes Spring 2027 — the retail gap remains the near-term custom-merch opportunity." },
    { name: "Mikecrack", type: "Creator", subs: 58.6, buzz: [7, 7, 7, 7, 7, 7, 7], interest: [72, 71, 71, 71, 71, 72, 72], rising: false,
      about: "Mikecrack is the most-subscribed Spanish YouTuber at ~58.6M subs (ranked #72 globally as of July 2026) and is enormous with younger and Spanish-speaking kids. The Los Compas trio (Mikecrack, ElTrollino, Timba VK) book series has sold 31M+ copies worldwide across 10+ titles. 'Mikecrack y la Superarma Secreta' — his animated-series live spectacular — has 2026/2027 tour dates on Ticketmaster Mexico, keeping the IP visibly in market." },
    { name: "Jelly", type: "Creator", subs: 23, buzz: [7, 5, 3, 3, 3, 3, 3], interest: [68, 59, 50, 39, 30, 22, 8], rising: false,
      about: "Jelly is a top kid-friendly Minecraft YouTuber (~23M subs) known for short, easy-to-watch videos. Ten-month slide continues into August 2026 — no new series, hook content, or franchise announcement; interest now at 8, a steady-state catalog name with no active trend drivers and no recovery signals in sight." },
    { name: "MrBeast Gaming", type: "Creator", subs: 42, buzz: [7, 7, 7, 7, 7, 7, 7], interest: [73, 71, 71, 71, 71, 70, 68], rising: false,
      about: "MrBeast Gaming is the gaming channel of mega-creator MrBeast — whose main channel crossed 500M subscribers on June 12, 2026, a YouTube first. The Gaming sub-channel (~42M subs) leans on big-budget Minecraft challenges, prizes, and spectacle. Less about one character and more about event-style videos kids love." },
    { name: "SSundee", type: "Creator", subs: 25.45, buzz: [8, 8, 9, 9, 9, 9, 9], interest: [64, 66, 72, 76, 79, 83, 90], rising: true,
      about: "SSundee (25.45M subs, ~4 uploads/week, 2.56% engagement) is a top US Minecraft creator known for funny commentary and pop-culture mod drops. The Crundee server series with Crainer (reunited 2026 after dormancy since 2019) continues actively — Crundee Craft modpack last updated July 19, 2026 (206K+ CurseForge downloads). Fan interest has climbed to 90, a new all-time high for this tracker — eleven consecutive weeks of upward movement with no official toy competition. Zero official toy line = strongest open US-creator custom merch slot alongside Alan Becker." },
    { name: "LankyBox", type: "Creator", subs: 42, buzz: [7, 5, 0, 0, 0, 0, 0], interest: [65, 55, 20, 9, 5, 1, 0], rising: false,
      about: "LankyBox is a 42M-sub duo known for 'brainrot'-style Minecraft skits. Confirmed quit — no uploads since ~April 2026 (31+ weeks); fan analysis videos and the Adam McArthur / Justin Kroma partnership-split story are the dominant narrative on TikTok. TikTok Shop (748K+ items sold historically) and retail remain live passively on existing SKUs at effectively zero interest. Channel is finished — do not invest in LankyBox-adjacent product for 2026-2027." },
    { name: "CaseOh", type: "Creator", subs: 10.84, buzz: [7, 8, 9, 9, 9, 9, 9], interest: [63, 68, 76, 82, 85, 86, 89], rising: true,
      about: "CaseOh has ~10.84M YouTube subscribers. The Summer Collection is active at caseohgames.com; a 'new-coming-soon' collection page is live — next apparel drop in preparation. A GamerSupps collaboration launched July 2026: Ghostbusters-inspired Pixel Cup ($25, pre-order closed July 17, ships ~Oct–Nov 2026), Nuclear Bombsicle energy drink, Big Boy Jug 64oz ($35), and CaseOh & Kitty Shirt. A warehouse reveal stream in late June went viral on TikTok (music studio, gym, pool, basketball court). Prior cadence (Winter → March → Summer → Fall) points to a fall 2026 drop — community anticipation is building in August. No official toy line exists = open US creator slot." },
    { name: "EYstreem", type: "Creator", subs: 13.76, buzz: [8, 8, 8, 8, 8, 8, 8], interest: [74, 76, 76, 77, 77, 82, 83], rising: true,
      about: "EYstreem is Australia's most-watched global gaming YouTuber (~13.76M subs). Spawnpoint Media — his production company — now employs 100+ people; Tubefilter June 2026: 'We didn't anticipate how strong the IP had become.' The Milo plush originally sold out (4,000 orders in ~2 weeks, zero paid marketing) and is confirmed back in stock at miloandchip.com; Chip plushie also available; EYstreem Variety Sticker Pack (EYstreem, Firelight, Milo, Chip designs) at eystreem.store. EYstreem's own subscriber growth is decelerated (~0.23%/month) while his Chip & Milo channel rips at 280K/month — the IP growth engine has shifted to the character brand. Spawnpoint Media is 'actively seeking brand partnerships and merchandise deals' as their primary business; no big-box retail expansion confirmed yet." },
    { name: "DanTDM", type: "Creator", subs: 29, buzz: [6, 6, 6, 6, 6, 6, 6], interest: [58, 58, 58, 57, 57, 54, 50], rising: false,
      about: "DanTDM is a long-running British Minecraft creator (~26M subs) active since 2012. Known for clean, family-friendly Let's Plays and mod showcases. In 2026 he is consulting with Mojang Studios and Merlin Entertainments on a Minecraft World theme-park development. A trusted, evergreen name with the kid audience." },
    { name: "PrestonPlayz", type: "Creator", subs: null, buzz: [7, 7, 9, 9, 9, 9, 9], interest: [62, 63, 72, 74, 75, 76, 76], rising: true,
      about: "PrestonPlayz's Bonkers Toys line is fully on shelf at Target and Amazon: Series 1 mini figures (Bloxton, PrestonPlayz, Preston 303, Shining Preston, Preston, Cactus Jones 6-pack), Mystery Merch Box (11 collectibles incl. limited-edition plushies, figures, posters, trading cards), plus the NAPPA Award-winning Pleb Slayer light-up sword and Mini Mystery Plush. Family of channels totals 66M combined subscribers and 22B views. Benchmark these SKUs for format and price-point — they are live competition on shelf now." },
    { name: "Dream", type: "Creator", subs: 31.5, buzz: [5, 5, 5, 5, 5, 5, 5], interest: [53, 52, 50, 47, 46, 38, 25], rising: false,
      about: "Dream (Clay) is one of the most famous US Minecraft names (~31.5M subs), known for 'Minecraft Manhunt' and speedrun content. His day-to-day Minecraft output has slowed, but the brand and faceless smiley logo are iconic. Recognition stays high even with kids who don't watch regularly. Slow interest erosion continues with no new hook to reverse the trend — interest at 25 as of August 2026." },
    { name: "Unspeakable", type: "Creator", subs: null, buzz: [5, 5, 5, 5, 5, 5, 5], interest: [51, 50, 50, 50, 50, 49, 47], rising: false,
      about: "Unspeakable is a 'loud,' high-energy creator known for challenges, builds and real-life crossovers. The big personality and colorful thumbnails play well with younger viewers. A long-standing staple of the kid-Minecraft scene." },
    { name: "TommyInnit", type: "Creator", subs: 12, buzz: [5, 5, 5, 4, 4, 4, 4], interest: [49, 49, 47, 41, 34, 26, 12], rising: false,
      about: "TommyInnit is a hugely popular British creator (~12M subs) who rose through Minecraft SMP servers and streams. He shifted to selective content in 2026 ('100 Questions with Tom Simons' interview series, first MC Championship appearance in ~2 years). Gradual audience drift continues — interest at 12 as of August 2026. He skews slightly older-kid/teen." },
    { name: "Wisp", type: "Creator", subs: null, buzz: [4, 4, 4, 4, 4, 4, 4], interest: [46, 44, 42, 37, 34, 25, 11], rising: false,
      about: "Wisp makes 'wild mod' Minecraft videos that are chaotic, funny and unpredictable. The light-hearted tone keeps it broadly kid-friendly. Slow drift continues — interest at 11 as of August 2026 with no major new hook to reverse the trend." },
    { name: "Stampy", type: "Creator", subs: null, buzz: [4, 3, 3, 3, 3, 3, 3], interest: [37, 35, 33, 29, 25, 15, 5], rising: false,
      about: "Stampy (Stampy Cat) is the original kid-safe Minecraft creator, voiced as a cheerful cartoon cat. His long-running 'Lovely World' series is wholesome and narrative. A nostalgic classic — more grandparent-familiar than kid-current in 2026; interest now at 5 and still fading." },
    { name: "Craftee", type: "Creator", subs: 5.2, buzz: [null, 6, 2, 2, 2, 2, 2], interest: [null, 50, 35, 23, 15, 5, 2], rising: false,
      about: "Craftee is a purely Minecraft-focused creator (~5M subs, ~12M monthly views) who appears on every curated 'kid-safe' list — no profanity, challenge and creative gameplay targeting ages 5–10. The craftee.store plush lineup (Classic Plushie $29.99, Golden variant, Chester plushie $26.99) remains available but generating no buzz. Subscriber growth stalled near zero; no franchise deals, retail expansion, or new drops detected through August 2026. Firmly catalog-only territory." },

    { name: "OMZ", type: "Creator", subs: 6.08, buzz: [null, null, 7, 7, 7, 7, 7], interest: [null, null, 60, 68, 72, 80, 84], rising: true,
      about: "OMZ (Omz Crew) is an American Minecraft roleplay YouTuber (~6.08M subscribers, gaining ~80K/month) generating ~32M monthly views as of August 2026. Active 'new member' and Crystal arc storylines sustain engagement — cross-platform narrative extends into Roblox. Merch at omzcrew.com, Amazon (full crew bundle), TikTok Shop, and Walmart; OMZ Squish Plushies available. WATCH: recent video titles ('OMZ LEFT...FOREVER?!' and 'The NEW Omz Member…') signal potential crew roster changes — monitor for audience disruption before committing product. No exclusive toy deal yet = open slot in the RP-server niche, but verify crew stability first." },

    { name: "Yarik Paw", type: "Creator", subs: 4.6, buzz: [null, null, null, null, 7, 8, 8], interest: [null, null, null, null, 57, 70, 73], rising: true,
      about: "Yarik Paw (@YarikPawGames) is a Ukrainian creator pioneering 'cinematic Minecraft' — episodic stories with emotional arcs and cliffhangers — at ~4.6M subscribers on his main Minecraft channel, 2.9B lifetime views. His secondary channel YarikPawReal (toy/food testing in reaction style) hit 880M+ views with one Short surpassing 68M views alone; 5.6M+ total subscribers across all channels and ~4B total views. Active PR campaign (BroadwayWorld, LA Weekly, GritDaily) sustains recognition heading into August; no toy or licensing deal found as of August 5 — notable white space given the defined character roster and proven appetite for story-Minecraft product." },

    // ---- FAN / ANIMATION CHARACTERS (merch-eligible — NOT Mojang's mobs) ----
    // Animated character duos — extremely high recognition w/ 6-10 y/o; CONFIRMED top sellers at Red Lava Toys shows.
    { name: "JJ & Mikey", type: "Character/Mob", subs: null, buzz: [10, 10, 10, 10, 10, 10, 10], interest: [96, 97, 98, 98, 98, 98, 99], rising: true,
      about: "JJ and Mikey are the lead characters of Maizen's animated Minecraft skits — now simultaneously live across four platforms: Hulu (Creator Essentials Season 1, 15 episodes), Tubi, Roku, and Ryan and Friends Plus, all streaming as of August 2026. Official JJ & Mikey plushies confirmed in stock at maizen.junipercreates.com; Carrie Cat & Banana Kid Plush Bundle live at $34.99 each. Pocket.watch deal confirms Scholastic books early 2027 and Bonkers Toys plush + blind-boxes Spring 2027 — the retail gap remains the near-term custom-merch opportunity. Confirmed #1 top sellers at Red Lava Toys shows." },
    { name: "Nico & Cash", type: "Character/Mob", subs: null, buzz: [10, 9, 9, 9, 9, 9, 9], interest: [90, 86, 87, 88, 88, 89, 89], rising: true,
      about: "Nico and Cash are a paired-character Minecraft animation duo — Cash's channel hit 11M subscribers on June 8, 2026; Nico at ~4.9M and climbing (30K new subs/month). Official plush line at cashandnico.com includes Nico Superhero, Cash Superhero, Shady, Toast Miner, Cash, and Nico plushies (9in Youtooz variant also available); Amazon shows 2,000+ units sold per month in Kids' Plush Toy Pillows. Steady at interest 89 — a durable catalog performer with proven show-table demand." },
    { name: "Chip & Milo", type: "Character/Mob", subs: 4.1, buzz: [9, 8, 9, 9, 9, 9, 9], interest: [85, 83, 90, 93, 94, 96, 97], rising: true,
      about: "Milo and Chip are an animated-Minecraft duo from EYstreem's Spawnpoint Media (4.1M subs, gaining ~280K/month — 4.52% monthly growth). 16 billion watch minutes May–Oct 2025 is comparable to SpongeBob SquarePants and 'well over half of Bluey's global watch minutes' for the same period (Tubefilter, June 2026). The Milo plush originally sold out (4,000 orders in ~2 weeks, zero paid marketing); confirmed back and now shipping at miloandchip.com; Chip plushie available; DTC + third-party Walmart listings. No big-box licensing deal confirmed yet — Spawnpoint Media is 'actively seeking brand partnerships and merchandise deals' as their primary business for the next 1-2 years. The SpongeBob-scale watch data makes this the single most underserved DTC-only IP on the board." },
    { name: "Alan Becker (AvM)", type: "Character/Mob", subs: 33.8, buzz: [8, 8, 9, 10, 10, 10, 10], interest: [70, 77, 85, 98, 99, 95, 97], rising: true,
      about: "Alan Becker's color-coded stick figures — The Second Coming, King Orange, Yellow, Green, Blue, and Red — star in 'Animation vs. Minecraft' (~33.8M subs). AVM Shorts Episode 40 (starring Red and Blue, confirmed via pop quiz at end of Ep 37) remains unreleased as of August 7 — now 16 weeks since Episode 39 'The Aether' (April 18, 2026); community anticipation is at absolute peak, with fans refreshing daily. The Animation VERSUS fighting game Kickstarter (co-created with DJ Welch and Muno) raised $1M+ from 11,845 backers in under 5 hours; July 28 update posted. An April 2026 Youtooz costume-variant plush drop (Sheriff Second Coming, Baker Red, Influencer Green, Chef Blue, Gamer Yellow — $29.99 each at alanbecker.shop) has proven sustained buyer appetite despite zero mass-retail presence. Zero mass-retail despite 33.8M+ subscribers: largest under-served retail white space in creator-Minecraft merch. Have sticker/print artwork ready — Ep 40 drop could be any moment." },

    // ---- FORMATS / TOPICS (what kind of videos they're glued to) ----
    { name: "'Minecraft BUT…'", type: "Format", subs: null, buzz: [7, 7, 7, 7, 7, 7, 7], interest: [61, 62, 62, 62, 62, 62, 62], rising: false,
      about: "'Minecraft BUT…' is a dominant format where a normal playthrough is twisted by one wild rule or mod (e.g. 'Minecraft BUT everything is giant'). It's build/challenge/reaction content that's endlessly remixable. CaseOh's Hardcore format is the current evolution of this template." },
    { name: "Brainrot skits", type: "Format", subs: null, buzz: [7, 6, 2, 1, 1, 1, 1], interest: [63, 60, 42, 27, 16, 7, 3], rising: false,
      about: "'Brainrot' skits are chaotic, sensory-overload short videos using Minecraft skins to act out absurd stories. LankyBox's TikTok Shop confirmed 748K+ items sold historically — this audience converts directly to buyers at high volume. LankyBox confirmed quit (31+ weeks, no uploads since ~April 2026) and no replacement creator has emerged as of August 2026. Format interest near-floor at 3." },
    { name: "Roleplay servers", type: "Format", subs: null, buzz: [5, 5, 5, 5, 6, 6, 6], interest: [46, 48, 51, 57, 64, 70, 76], rising: true,
      about: "Minecraft roleplay (RP) servers are fictional worlds with their own economies, governments and ongoing storylines. OMZ Crew's active storylines continue driving the format — though watch for crew-roster uncertainty flagged in recent OMZ titles. Interest at 76 as of August 7, still the strongest rising format on the board. Popular with kids who love the 'pretend' and community side." },

    // ---- MOJANG IP — official game content (CUSTOMER AWARENESS ONLY, not merch) ----
    { name: "Baby mobs (Tiny Takeover)", type: "Character/Mob", ip: "mojang", subs: null, buzz: [4, 4, 2, 2, 1, 0, 0], interest: [50, 43, 28, 14, 5, 1, 0], rising: false,
      about: "The March 2026 'Tiny Takeover' drop redesigned every baby farm animal — puppies, kittens, piglets, calves, chicks, lambs, ocelots and bunnies — for maximum cuteness. Now 5 months post-launch, the initial viral wave has fully settled and interest is at zero. Official Mojang content: great to know about for customer chats, but NOT something Red Lava Toys can make merch of." },
    { name: "Sulfur cube", type: "Character/Mob", ip: "mojang", subs: null, buzz: [6, 6, 6, 6, 6, 6, 6], interest: [54, 55, 55, 56, 56, 57, 58], rising: true,
      about: "The sulfur cube is a Minecraft mob that can absorb blocks — a mechanic unlike anything else in the game, driving lots of reaction/explainer videos. Official Mojang content: worth knowing for customer conversations, but not merch-eligible for Red Lava Toys." },
    { name: "A Minecraft Movie", type: "Format", ip: "mojang", subs: null, buzz: [6, 7, 9, 9, 9, 9, 7], interest: [62, 68, 75, 77, 78, 70, 56], rising: false,
      about: "The live-action/animated Warner Bros. film (April 2025) continues to drive streaming discovery; post-Summer-Sale cooling continues with interest now at 56. Sequel 'A Minecraft Movie Squared' (July 23, 2027) filming in New Zealand — confirmed cast includes Momoa, Black, Brooks, Myers, Hansen, Coolidge returning, plus Kirsten Dunst as Alex; Matt Berry in a mystery role. Mojang/WB IP — strong customer-conversation context, not merch-eligible for Red Lava Toys." },
    { name: "Netflix Minecraft Series", type: "Format", ip: "mojang", subs: null, buzz: [null, null, 9, 9, 9, 7, 5], interest: [null, null, 74, 89, 86, 72, 55], rising: false,
      about: "WildBrain/Flying Bark CG-animated series (head writer: A.C. Bradley, Carmen Sandiego/Marvel's What If...?; showrunners Kevin Adams and Joe Ksander) premiered June 24, 2026 on Netflix. Seven weeks post-launch as of August 7: no Netflix Top 10 appearance confirmed, no character names released in wide press, no Season 2 announcement — interest cooling to 55. Fan art and reaction content continue at low velocity. Produced under Mojang/Netflix license — monitor for a Top 10 entry or character name reveals. NOT merch-eligible for Red Lava Toys." },
    { name: "Minecraft Dungeons II", type: "Format", ip: "mojang", subs: null, buzz: [null, null, null, null, 5, 6, 9], interest: [null, null, null, null, 42, 55, 84], rising: true,
      about: "Minecraft Dungeons II is the sequel to Mojang's dungeon-crawling game — CONFIRMED release date September 29, 2026 (53 days away) across PC, PS5, Xbox Series X/S, Nintendo Switch, Switch 2, and Game Pass day one. LEGO set 21591 'The Twisted Warden Battle' (438 pieces, $59.99, 4 new hero minifigures: Kellen, Ren, Flores, Valorie) is on shelf now. Mattel plush also now on shelf: Twisted Warden Plush (8in, JMG99), Blub Plush (8in, JMG98), and Baby Sifter Plush (8in, JMG97) — all live at shop.mattel.com. The new hero characters are likely to drive 'dress as my Dungeons II hero' custom-skin demand in the September release window. Official Mojang content — great for customer conversation, NOT merch-eligible for Red Lava Toys." }
  ],

  // Merch-eligible names ONLY (never Mojang IP).
  movers: {
    up:   ["Alan Becker (AvM)", "SSundee", "Chip & Milo", "Maizen"],
    down: ["Jelly", "Dream", "TommyInnit"],
    new:  []
  },

  headline: "AUG 7 — ALAN BECKER (AvM): Ep 40 (Red & Blue) STILL unreleased — now 16 WEEKS since Ep 39 (Apr 18); each passing day amplifies the drop moment; 33.8M subs, zero mass retail = biggest open white space in creator merch — sticker/print artwork must be ready NOW. MAIZEN: JJ & Mikey now simultaneously streaming on Hulu + Tubi + Roku + Ryan and Friends Plus; buzz raised to 10; Bonkers Spring 2027 retail gap still open = best near-term custom-merch window. CHIP & MILO: SpongeBob-scale watch data, Prime Video live, no big-box deal = most underserved IP on the board. SSUNDEE: interest 90 (new all-time high), Crundee active, zero toy line = strongest open US-creator slot. APHMAU: five retailers live in August (Amazon, Walmart, Target, Claire's, Smyths) — complementary products only. OMZ: WATCH crew-roster stability before investing ('OMZ LEFT...FOREVER?!' titles in feed). (Mojang: Dungeons II Sept 29 — 53 days out, LEGO + Mattel plush now both on shelf, interest 84 and rising; Netflix Series 7 wks in, still no Top 10, interest 55; Movie cooling to 56 — all Mojang IP, not merch-eligible.)"
};
